language: rust
matrix:
  include:
    - os: linux
      sudo: required
      addons:
        apt:
          packages:
            - vim
            - automake
    - os: osx
      osx_image: xcode7.2

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then apt-get update && apt-get install libfuse-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew outdated osxfuse || brew install osxfuse; fi
script: echo hello
