language: csharp
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
          - gettext
          - libcurl4-openssl-dev
          - libicu-dev
          - libssl-dev
          - libunwind8
          - zlib1g
      env:
        - KOREBUILD_DNU_RESTORE_CORECLR=true KOREBUILD_TEST_DNXCORE=true
      mono:
        - 4.0.5env: EDITOR=nvim
    - language: generic
      os: osx
      osx_image: xcode7.2b3
      env:
        - KOREBUILD_DNU_RESTORE_CORECLR=true KOREBUILD_TEST_DNXCORE=true
      mono:
        - 4.0.5env: EDITOR=nvim

script:
  - ./build.sh verify
