language: objective-c

matrix:
  include:
    - os: osx
    - osx_image: xcode6.4
    - osx_image: xcode7
    - osx_image: xcode7.1
    - osx_image: xcode7.2
    - osx_image: xcode7.3

script: echo sayHi