language: rust
matrix:
  include:
    - os: linux
      sudo: false
      addons:
        apt:
          packages:
            - vim
            - automake
    - os: osx
      osx_image: xcode7.2

install: true
script: echo hello
