osx_image: xcode7.3
language: objective-c
xcode_project: ios/Link.xcodeproj/
xcode_scheme: TOL
before_script:
  - echo hi
script: xctool -project ios/Link.xcodeproj/ -scheme 'TOL' -configuration Debug -sdk iphoneos9.3 build

after_script:
  - echo hola
