language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      install: true
      script: echo hola
    - os: linux
      sudo: false
      addons:
        apt:
          packages:
            - vim
            - automake
            - pkg-config
            - libpcre3-dev
            - zlib1g-dev
      install: true
      script: echo hola
    - os: linux
      sudo: required
      install: true
      script: echo hola
